language: php

php:
  - 8.0
  - 8.1
  - 8.2
  - 8.3
  - 8.4

before_script:
  - travis_retry composer self-update
  - travis_retry composer update
  - travis_retry composer install --prefer-source --no-interaction --dev

script: phpunit
